### ISSUE TITLE
Invalid HTML

### ISSUE THREAD

**Issue by benorgan** [dh996699/InstanewsProject#1]
There are 4 validation errors with the HTML (as tested by Validity), this seems to happen on every page and is due to incorrect image attributes. 

`VM189:1 line 17: An “img” element must have an “alt” attribute, except under certain conditions. For details, consult guidance on providing text alternatives for images.
VM189:1 line 19: Bad value “50px” for attribute “width” on element “img”: Expected a digit but saw “p” instead.
VM189:1 line 19: Bad value “50px” for attribute “height” on element “img”: Expected a digit but saw “p” instead.
VM189:1 line 19: An “img” element must have an “alt” attribute, except under certain conditions. For details, consult guidance on providing text alternatives for images.`

**Comment by dh996699** [comment]
Already fixed but can't push back to git hub.
